#!/bin/sh
#
# dbxmld_wrapper - wrapper script for dbxmld on FreeBSD
#
# This goes in /usr/local/sbin.  It runs dbxmld in a loop.  If dbxmld
# exits then the script restarts it automatically.
#
# The -D flag tells dbxmld to *not* put itself into the background,
# and the -C flag tells it to get the rest of its configuration from
# the specified config file.

while true ; do
    /usr/local/sbin/dbxmld -D -C /usr/local/www/dbxmld_config
    if [ -f /var/run/nologin ] ; then
	exit
    fi
    sleep 10
    egrep ' dbxmld\[' /var/log/messages |
      tail -33 |
      mail -s "dbxmld on `hostname` restarted" root
done
