#!/bin/sh
#
# xdbms_wrapper - wrapper script for xdbms on FreeBSD
#
# This goes in /usr/local/sbin.  It runs xdbms in a loop.  If xdbms
# exits then the script restarts it automatically.
#
# The -D flag tells xdbms to *not* put itself into the background,
# and the -C flag tells it to get the rest of its configuration from
# the specified config file.

while true ; do
    /usr/local/sbin/xdbms -D -C /usr/local/www/xdbms_config
    if [ -f /var/run/nologin ] ; then
	exit
    fi
    sleep 10
    egrep ' xdbms\[' /var/log/messages |
      tail -33 |
      mail -s "xdbms on `hostname` restarted" root
done
